"""project history changes

Revision ID: 2d6edec30ea7
Revises: be47a315c079
Create Date: 2025-11-19 00:34:44.844079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6edec30ea7'
down_revision: Union[str, Sequence[str], None] = 'be47a315c079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_history', sa.Column('changes', sa.JSON(), nullable=True, comment='JSON object of all changes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_history', 'changes')
    # ### end Alembic commands ###
