"""project history changes-1

Revision ID: 85ec5960e059
Revises: 2d6edec30ea7
Create Date: 2025-11-19 00:42:28.676217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ec5960e059'
down_revision: Union[str, Sequence[str], None] = '2d6edec30ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_history', sa.Column('description', sa.Text(), nullable=True, comment='Human readable description'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_history', 'description')
    # ### end Alembic commands ###
