"""task history and log models changed

Revision ID: be47a315c079
Revises: c02eed930613
Create Date: 2025-11-13 23:03:02.815785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be47a315c079'
down_revision: Union[str, Sequence[str], None] = 'c02eed930613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('created', 'updated', 'status_changed', 'assigned', 'reassigned', 'comment_added', 'time_logged', name='historyaction'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True, comment='Field that was changed'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='Previous value'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='New value'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='JSON object of all changes'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human readable description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False, comment='Time spent in hours'),
    sa.Column('description', sa.Text(), nullable=True, comment='What was done during this time'),
    sa.Column('log_date', sa.DateTime(timezone=True), nullable=False, comment='Date when work was done'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_logs_id'), 'time_logs', ['id'], unique=False)
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='taskpriority'), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('estimated_hours', sa.Float(), nullable=True, comment='Estimated time in hours'))
    op.add_column('tasks', sa.Column('actual_hours', sa.Float(), nullable=True, comment='Total logged time in hours'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'priority')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_index(op.f('ix_time_logs_id'), table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.drop_table('task_history')
    # ### end Alembic commands ###
